# Generated by Django 3.1.6 on 2021-02-16 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=50)),
                ('time_limit', models.PositiveIntegerField()),
                ('words_count', models.PositiveIntegerField(default=0)),
                ('quiz_language', models.CharField(max_length=2)),
                ('questions_count', models.PositiveIntegerField(default=0)),
                ('best_attempt', models.CharField(default='N/A', max_length=10)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_word', models.CharField(max_length=75)),
                ('word_definition', models.TextField()),
                ('part_of_speech', models.CharField(max_length=20)),
                ('example', models.TextField()),
                ('synonyms', models.TextField()),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_list.quizlist')),
            ],
        ),
    ]
