# Generated by Django 3.1.6 on 2021-02-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizlist',
            name='quiz_language',
            field=models.CharField(choices=[('EN', 'English'), ('ZH', 'Chinese'), ('FR', 'French'), ('JA', 'Japanese'), ('KO', 'Korean'), ('RU', 'Russian')], max_length=2),
        ),
    ]
