# Generated by Django 3.1.6 on 2021-02-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_list', '0002_auto_20210216_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizlist',
            name='quiz_language',
            field=models.CharField(choices=[('en', 'English'), ('zh', 'Chinese'), ('fr', 'French'), ('ja', 'Japanese'), ('ko', 'Korean'), ('ru', 'Russian')], max_length=2),
        ),
    ]
