# Generated by Django 3.1.6 on 2021-02-17 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_list', '0003_auto_20210216_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='example',
        ),
        migrations.RemoveField(
            model_name='word',
            name='synonyms',
        ),
    ]
